export const menProducts = [
  {
    id: "n1",
    name: "Nike Air Max 95 Big Bubble",
    category: "Lifestyle",
    price: 4999000,
    oldPrice: 0,
    rating: 4.8,
    tag: "Hot",
    season: 2026,
    image: "../img/W+NIKE+AIR+MAX+95+BIG+BUBBLE.jpg",
    desc: "Thiết kế cổ điển với công nghệ Air nổi bật, mang lại cảm giác êm ái.",
    sizes: [39, 40, 41, 42, 43],
  },
  {
    id: "n2",
    name: "Nike Air Force 1 '07",
    category: "Lifestyle",
    price: 3239000,
    oldPrice: 0,
    rating: 4.9,
    tag: "Best seller",
    season: 2026,
    image: "../img/AIR+FORCE+1+'07.jpg",
    desc: "Mẫu giày huyền thoại với thiết kế đơn giản, dễ phối đồ.",
    sizes: [38, 39, 40, 41, 42, 43],
  },
  {
    id: "n3",
    name: "Nike ACG Pegasus Trail",
    category: "Outdoor",
    price: 4109000,
    oldPrice: 0,
    rating: 4.7,
    tag: "Trail",
    season: 2026,
    image: "../img/NIKE+ACG+PEGASUS+TRAIL.jpg",
    desc: "Thiết kế chuyên dụng cho địa hình, đế bám tốt và chống trượt.",
    sizes: [40, 41, 42, 43, 44],
  },
  {
    id: "n4",
    name: "Air Jordan 1 Mid SE",
    category: "Basketball",
    price: 3959000,
    oldPrice: 0,
    rating: 4.9,
    tag: "Classic",
    season: 2026,
    image: "../img/AIR+JORDAN+1+MID+SE.jpg",
    desc: "Phong cách bóng rổ cổ điển, biểu tượng của Jordan.",
    sizes: [39, 40, 41, 42, 43],
  },
  {
    id: "n5",
    name: "Jordan Spizike G",
    category: "Lifestyle",
    price: 5589000,
    oldPrice: 0,
    rating: 4.6,
    tag: "Premium",
    season: 2026,
    image: "../img/JORDAN+SPIZIKE+G.jpg",
    desc: "Thiết kế kết hợp nhiều dòng Jordan, tạo điểm nhấn độc đáo.",
    sizes: [40, 41, 42, 43, 44],
  },
  {
    id: "n6",
    name: "Jordan Sixty Plus Low",
    category: "Lifestyle",
    price: 4849000,
    oldPrice: 0,
    rating: 4.6,
    tag: "Retro",
    season: 2025,
    image: "../img/JORDAN+SIXTY+PLUS+LOW.jpg",
    desc: "Lấy cảm hứng từ các cột mốc 60 điểm của Michael Jordan.",
    sizes: [40, 41, 42, 43],
  },
  {
    id: "n7",
    name: "Nike Pegasus 42",
    category: "Running",
    price: 3829000,
    oldPrice: 0,
    rating: 4.8,
    tag: "Running",
    season: 2026,
    image: "../img/AIR+ZOOM+PEGASUS+42.jpg",
    desc: "Giày chạy nhẹ, đệm tốt, phù hợp luyện tập hằng ngày.",
    sizes: [39, 40, 41, 42, 43],
  },
  {
    id: "n8",
    name: "Nike Dunk Low Retro SE",
    category: "Lifestyle",
    price: 3519000,
    oldPrice: 0,
    rating: 4.7,
    tag: "Street",
    season: 2026,
    image: "../img/NIKE+DUNK+LOW+RETRO+SE.jpg",
    desc: "Phong cách streetwear trẻ trung, dễ phối outfit.",
    sizes: [39, 40, 41, 42],
  },
  {
    id: "n9",
    name: "Nike Shox Ride 2",
    category: "Running",
    price: 4999000,
    oldPrice: 0,
    rating: 4.7,
    tag: "Tech",
    season: 2025,
    image: "../img/NIKE+SHOX+RIDE+2.jpg",
    desc: "Công nghệ Shox độc đáo giúp hấp thụ lực và tăng độ nảy.",
    sizes: [40, 41, 42, 43],
  },
  {
    id: "n10",
    name: "Nike Zoom Vomero 5 SE",
    category: "Running",
    price: 4999999,
    oldPrice: 0,
    rating: 4.9,
    tag: "Premium",
    season: 2026,
    image: "../img/NIKE+ZOOM+VOMERO+5+SE.jpg",
    desc: "Đệm Zoom cao cấp, mang lại trải nghiệm chạy êm ái tối đa.",
    sizes: [39, 40, 41, 42, 43],
  },
];

export const womenProducts = [
  {
    id: "n1",
    name: "Nike Air Max 95 Big Bubble",
    category: "Lifestyle",
    price: 4999000,
    oldPrice: 0,
    rating: 4.8,
    tag: "Hot",
    season: 2026,
    image: "../img/W+NIKE+AIR+MAX+95+BIG+BUBBLE.jpg",
    desc: "Thiết kế cổ điển với công nghệ Air nổi bật, mang lại cảm giác êm ái.",
    sizes: [39, 40, 41, 42, 43],
  },
  {
    id: "n2",
    name: "Nike Air Force 1 '07",
    category: "Lifestyle",
    price: 3239000,
    oldPrice: 0,
    rating: 4.9,
    tag: "Best seller",
    season: 2026,
    image: "../img/AIR+FORCE+1+'07.jpg",
    desc: "Mẫu giày huyền thoại với thiết kế đơn giản, dễ phối đồ.",
    sizes: [38, 39, 40, 41, 42, 43],
  },
  {
    id: "n3",
    name: "Nike ACG Pegasus Trail",
    category: "Outdoor",
    price: 4109000,
    oldPrice: 0,
    rating: 4.7,
    tag: "Trail",
    season: 2026,
    image: "../img/NIKE+ACG+PEGASUS+TRAIL.jpg",
    desc: "Thiết kế chuyên dụng cho địa hình, đế bám tốt và chống trượt.",
    sizes: [40, 41, 42, 43, 44],
  },
  {
    id: "n4",
    name: "Air Jordan 1 Mid SE",
    category: "Basketball",
    price: 3959000,
    oldPrice: 0,
    rating: 4.9,
    tag: "Classic",
    season: 2026,
    image: "../img/AIR+JORDAN+1+MID+SE.jpg",
    desc: "Phong cách bóng rổ cổ điển, biểu tượng của Jordan.",
    sizes: [39, 40, 41, 42, 43],
  },
  {
    id: "n5",
    name: "Jordan Spizike G",
    category: "Lifestyle",
    price: 5589000,
    oldPrice: 0,
    rating: 4.6,
    tag: "Premium",
    season: 2026,
    image: "../img/JORDAN+SPIZIKE+G.jpg",
    desc: "Thiết kế kết hợp nhiều dòng Jordan, tạo điểm nhấn độc đáo.",
    sizes: [40, 41, 42, 43, 44],
  },
  {
    id: "n6",
    name: "Jordan Sixty Plus Low",
    category: "Lifestyle",
    price: 4849000,
    oldPrice: 0,
    rating: 4.6,
    tag: "Retro",
    season: 2025,
    image: "../img/JORDAN+SIXTY+PLUS+LOW.jpg",
    desc: "Lấy cảm hứng từ các cột mốc 60 điểm của Michael Jordan.",
    sizes: [40, 41, 42, 43],
  },
  {
    id: "n7",
    name: "Nike Pegasus 42",
    category: "Running",
    price: 3829000,
    oldPrice: 0,
    rating: 4.8,
    tag: "Running",
    season: 2026,
    image: "../img/AIR+ZOOM+PEGASUS+42.jpg",
    desc: "Giày chạy nhẹ, đệm tốt, phù hợp luyện tập hằng ngày.",
    sizes: [39, 40, 41, 42, 43],
  },
  {
    id: "n8",
    name: "Nike Dunk Low Retro SE",
    category: "Lifestyle",
    price: 3519000,
    oldPrice: 0,
    rating: 4.7,
    tag: "Street",
    season: 2026,
    image: "../img/NIKE+DUNK+LOW+RETRO+SE.jpg",
    desc: "Phong cách streetwear trẻ trung, dễ phối outfit.",
    sizes: [39, 40, 41, 42],
  },
  {
    id: "n9",
    name: "Nike Shox Ride 2",
    category: "Running",
    price: 4999000,
    oldPrice: 0,
    rating: 4.7,
    tag: "Tech",
    season: 2025,
    image: "../img/NIKE+SHOX+RIDE+2.jpg",
    desc: "Công nghệ Shox độc đáo giúp hấp thụ lực và tăng độ nảy.",
    sizes: [40, 41, 42, 43],
  },
  {
    id: "n10",
    name: "Nike Zoom Vomero 5 SE",
    category: "Running",
    price: 4999999,
    oldPrice: 0,
    rating: 4.9,
    tag: "Premium",
    season: 2026,
    image: "../img/NIKE+ZOOM+VOMERO+5+SE.jpg",
    desc: "Đệm Zoom cao cấp, mang lại trải nghiệm chạy êm ái tối đa.",
    sizes: [39, 40, 41, 42, 43],
  },
];
