export const menProducts = [
  {
    id: "n1",
    name: "Nike Air Max 95 Big Bubble",
    category: "Lifestyle",
    price: 4199000,
    oldPrice: 4999000,
    rating: 4.8,
    tag: "Hot",
    season: 2026,
    image: "../img/W+NIKE+AIR+MAX+95+BIG+BUBBLE.jpg",
    desc: "Thiết kế cổ điển với công nghệ Air nổi bật, mang lại cảm giác êm ái.",
    sizes: [39, 40, 41, 42, 43],
  },
  {
    id: "n2",
    name: "Nike Air Force 1 '07",
    category: "Lifestyle",
    price: 3239000,
    oldPrice: 0,
    rating: 4.9,
    tag: "Best seller",
    season: 2026,
    image: "../img/AIR+FORCE+1+'07.jpg",
    desc: "Mẫu giày huyền thoại với thiết kế đơn giản, dễ phối đồ.",
    sizes: [38, 39, 40, 41, 42, 43],
  },
  {
    id: "n3",
    name: "Nike ACG Pegasus Trail",
    category: "Outdoor",
    price: 3399000,
    oldPrice: 4109000,
    rating: 4.7,
    tag: "Trail",
    season: 2026,
    image: "../img/NIKE+ACG+PEGASUS+TRAIL.jpg",
    desc: "Thiết kế chuyên dụng cho địa hình, đế bám tốt và chống trượt.",
    sizes: [40, 41, 42, 43, 44],
  },
  {
    id: "n4",
    name: "Air Jordan 1 Mid SE",
    category: "Basketball",
    price: 3959000,
    oldPrice: 0,
    rating: 4.9,
    tag: "Classic",
    season: 2026,
    image: "../img/AIR+JORDAN+1+MID+SE.jpg",
    desc: "Phong cách bóng rổ cổ điển, biểu tượng của Jordan.",
    sizes: [39, 40, 41, 42, 43],
  },
  {
    id: "n5",
    name: "Jordan Spizike G",
    category: "Lifestyle",
    price: 4599000,
    oldPrice: 5589000,
    rating: 4.6,
    tag: "Premium",
    season: 2026,
    image: "../img/JORDAN+SPIZIKE+G.jpg",
    desc: "Thiết kế kết hợp nhiều dòng Jordan, tạo điểm nhấn độc đáo.",
    sizes: [40, 41, 42, 43, 44],
  },
  {
    id: "n6",
    name: "Jordan Sixty Plus Low",
    category: "Lifestyle",
    price: 4849000,
    oldPrice: 0,
    rating: 4.6,
    tag: "Retro",
    season: 2025,
    image: "../img/JORDAN+SIXTY+PLUS+LOW.jpg",
    desc: "Lấy cảm hứng từ các cột mốc 60 điểm của Michael Jordan.",
    sizes: [40, 41, 42, 43],
  },
  {
    id: "n7",
    name: "Nike Pegasus 42",
    category: "Running",
    price: 2999000,
    oldPrice: 3829000,
    rating: 4.8,
    tag: "Running",
    season: 2026,
    image: "../img/AIR+ZOOM+PEGASUS+42.jpg",
    desc: "Giày chạy nhẹ, đệm tốt, phù hợp luyện tập hằng ngày.",
    sizes: [39, 40, 41, 42, 43],
  },
  {
    id: "n8",
    name: "Nike Dunk Low Retro SE",
    category: "Lifestyle",
    price: 3519000,
    oldPrice: 0,
    rating: 4.7,
    tag: "Street",
    season: 2026,
    image: "../img/NIKE+DUNK+LOW+RETRO+SE.jpg",
    desc: "Phong cách streetwear trẻ trung, dễ phối outfit.",
    sizes: [39, 40, 41, 42],
  },
  {
    id: "n9",
    name: "Nike Shox Ride 2",
    category: "Running",
    price: 4999000,
    oldPrice: 0,
    rating: 4.7,
    tag: "Tech",
    season: 2025,
    image: "../img/NIKE+SHOX+RIDE+2.jpg",
    desc: "Công nghệ Shox độc đáo giúp hấp thụ lực và tăng độ nảy.",
    sizes: [40, 41, 42, 43],
  },
  {
    id: "n10",
    name: "Nike Zoom Vomero 5 SE",
    category: "Running",
    price: 3999000,
    oldPrice: 4999999,
    rating: 4.9,
    tag: "Premium",
    season: 2026,
    image: "../img/NIKE+ZOOM+VOMERO+5+SE.jpg",
    desc: "Đệm Zoom cao cấp, mang lại trải nghiệm chạy êm ái tối đa.",
    sizes: [39, 40, 41, 42, 43],
  },
];

export const womenProducts = [
  {
    id: "w1",
    name: "Nike Shox Z",
    category: "Running",
    price: 3299000,
    oldPrice: 3829000,
    rating: 4.7,
    tag: "Tech",
    season: 2026,
    image: "../img/W+NIKE+SHOX+Z.png",
    desc: "Thiết kế Shox mang lại độ đàn hồi và hỗ trợ lực tốt khi di chuyển.",
    sizes: [36, 37, 38, 39, 40, 41],
  },
  {
    id: "w2",
    name: "Jordan Flight Court SE",
    category: "Basketball",
    price: 3239000,
    oldPrice: 0,
    rating: 4.6,
    tag: "Court",
    season: 2026,
    image: "../img/WMNS+JORDAN+FLIGHT+COURT+SE.png",
    desc: "Phong cách bóng rổ hiện đại, nhẹ và linh hoạt.",
    sizes: [36, 37, 38, 39, 40],
  },
  {
    id: "w3",
    name: "Nike Air Max Koko SE",
    category: "Lifestyle",
    price: 2799000,
    oldPrice: 3239000,
    rating: 4.8,
    tag: "Sandal",
    season: 2026,
    image: "../img/W+AIR+MAX+KOKO+SANDAL+SE.png",
    desc: "Dáng sandal Air Max thời trang, cực kỳ thoải mái.",
    sizes: [36, 37, 38, 39, 40],
  },
  {
    id: "w4",
    name: "Air Jordan 1 Low SE",
    category: "Lifestyle",
    price: 3669000,
    oldPrice: 0,
    rating: 4.9,
    tag: "Classic",
    season: 2026,
    image: "../img/WMNS+AIR+JORDAN+1+LOW+SE.png",
    desc: "Phiên bản low-top kinh điển, dễ phối outfit hằng ngày.",
    sizes: [36, 37, 38, 39, 40, 41],
  },
  {
    id: "w5",
    name: "Nike Air Max Muse",
    category: "Lifestyle",
    price: 3599000,
    oldPrice: 4409000,
    rating: 4.8,
    tag: "Premium",
    season: 2026,
    image: "../img/WMNS+NIKE+AIR+MAX+MUSE.png",
    desc: "Thiết kế Air Max hiện đại, êm và nổi bật.",
    sizes: [36, 37, 38, 39, 40],
  },
  {
    id: "w6",
    name: "Nike Air Max Moto 2K",
    category: "Running",
    price: 3669000,
    oldPrice: 0,
    rating: 4.7,
    tag: "Retro",
    season: 2026,
    image: "../img/W+NIKE+AIR+MAX+MOTO+2K.png",
    desc: "Phong cách retro Y2K kết hợp đệm Air êm ái.",
    sizes: [37, 38, 39, 40, 41],
  },
  {
    id: "w7",
    name: "Nike ACG Pegasus Trail",
    category: "Outdoor",
    price: 3399000,
    oldPrice: 4109000,
    rating: 4.7,
    tag: "Trail",
    season: 2026,
    image: "../img/W+NIKE+ACG+PEGASUS+TRAIL.png",
    desc: "Giày địa hình bám tốt, phù hợp outdoor và trekking nhẹ.",
    sizes: [37, 38, 39, 40, 41, 42],
  },
  {
    id: "w8",
    name: "Nike Pegasus Premium",
    category: "Running",
    price: 4999000,
    oldPrice: 6179000,
    rating: 4.9,
    tag: "Premium",
    season: 2026,
    image: "../img/W+NIKE+PEGASUS+PREMIUM.png",
    desc: "Dòng Pegasus cao cấp, tối ưu cho chạy bộ đường dài.",
    sizes: [37, 38, 39, 40, 41, 42],
  },
  {
    id: "w9",
    name: "Nike Vomero 18",
    category: "Running",
    price: 4259000,
    oldPrice: 0,
    rating: 4.8,
    tag: "Comfort",
    season: 2026,
    image: "../img/W+NIKE+VOMERO+18.png",
    desc: "Đệm cực êm, hỗ trợ tốt cho chạy và đi bộ dài.",
    sizes: [37, 38, 39, 40, 41],
  },
  {
    id: "w10",
    name: "Nike Air Superfly",
    category: "Running",
    price: 3239000,
    oldPrice: 0,
    rating: 4.6,
    tag: "Light",
    season: 2026,
    image: "../img/W+NIKE+AIR+SUPERFLY+FMME.png",
    desc: "Thiết kế nhẹ, thoáng khí, phù hợp vận động hằng ngày.",
    sizes: [36, 37, 38, 39, 40],
  },
  {
    id: "w11",
    name: "Nike Dunk Low Suede",
    category: "Lifestyle",
    price: 2699000,
    oldPrice: 3239000,
    rating: 4.7,
    tag: "Street",
    season: 2026,
    image: "../img/WMNS+NIKE+DUNK+LOW.png",
    desc: "Phong cách streetwear mềm mại với chất liệu suede.",
    sizes: [36, 37, 38, 39, 40, 41],
  },
  {
    id: "w12",
    name: "Nike Air Force 1 '07",
    category: "Lifestyle",
    price: 2929000,
    oldPrice: 0,
    rating: 4.9,
    tag: "Best seller",
    season: 2026,
    image: "../img/WMNS+AIR+FORCE+1+'07.png",
    desc: "Huyền thoại Air Force 1 với thiết kế đơn giản, dễ phối.",
    sizes: [36, 37, 38, 39, 40, 41],
  },
  {
    id: "w13",
    name: "Nike Air Force 1 '07 Essential",
    category: "Lifestyle",
    price: 2299000,
    oldPrice: 2649000,
    rating: 4.8,
    tag: "Essential",
    season: 2026,
    image: "../img/WMNS+AIR+FORCE+1+'07+ESS.png",
    desc: "Phiên bản Essential tối giản, phù hợp mọi outfit.",
    sizes: [36, 37, 38, 39, 40],
  },
];
